src/Entity/Command/Contact/CommandContactCreate.php
<?php

namespace App\Entity\Command\Contact;

use App\CQRS\Entity\Command\CommandEntityInterface;
use Symfony\Component\Validator\Constraints as Assert;

class CommandContactCreate implements CommandEntityInterface
{
    #[Assert\Length(min: 2)]
    private string $name;

    #[Assert\Length(min: 0, max: 64)]
    private ?string $givenName = null;

    #[Assert\Length(min: 0, max: 64)]
    private ?string $famillyName = null;

    #[Assert\Length(min: 5)]
    private ?string $address = null;

    #[Assert\Length(min: 5, max: 5)]
    private ?string $postalCode = null;

    #[Assert\Length(min: 2)]
    private ?string $city = null;

    #[Assert\Length(min: 10, max: 20)]
    private ?string $phone = null;

    #[Assert\Email]
    private ?string $email = null;

    public function getName(): string
    {
        return $this->name;
    }

    public function setName(string $name): CommandContactCreate
    {
        $this->name = $name;

        return $this;
    }

    public function getGivenName(): ?string
    {
        return $this->givenName;
    }

    public function setGivenName(?string $givenName): CommandContactCreate
    {
        $this->givenName = $givenName;

        return $this;
    }

    public function getFamillyName(): ?string
    {
        return $this->famillyName;
    }

    public function setFamillyName(?string $famillyName): CommandContactCreate
    {
        $this->famillyName = $famillyName;

        return $this;
    }

    public function getAddress(): ?string
    {
        return $this->address;
    }

    public function setAddress(?string $address): CommandContactCreate
    {
        $this->address = $address;

        return $this;
    }

    public function getPostalCode(): ?string
    {
        return $this->postalCode;
    }

    public function setPostalCode(?string $postalCode): CommandContactCreate
    {
        $this->postalCode = $postalCode;

        return $this;
    }

    public function getCity(): ?string
    {
        return $this->city;
    }

    public function setCity(?string $city): CommandContactCreate
    {
        $this->city = $city;

        return $this;
    }

    public function getPhone(): ?string
    {
        return $this->phone;
    }

    public function setPhone(?string $phone): CommandContactCreate
    {
        $this->phone = $phone;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(?string $email): CommandContactCreate
    {
        $this->email = $email;

        return $this;
    }
}

src/Entity/Command/Contact/CommandContactDelete.php
<?php

namespace App\Entity\Command\Contact;

use App\CQRS\Entity\Command\CommandEntityInterface;
use Symfony\Component\Uid\Uuid;
use Symfony\Component\Validator\Constraints as Assert;

class CommandContactDelete implements CommandEntityInterface
{
    #[Assert\Uuid]
    private Uuid $id;

    public function getId(): Uuid
    {
        return $this->id;
    }

    public function setId(Uuid $id): CommandContactDelete
    {
        $this->id = $id;

        return $this;
    }
}

src/Entity/Command/Contact/CommandContactEditAddress.php
<?php

namespace App\Entity\Command\Contact;

use App\CQRS\Entity\Command\CommandEntityInterface;
use Symfony\Component\Uid\Uuid;
use Symfony\Component\Validator\Constraints as Assert;

class CommandContactEditAddress implements CommandEntityInterface
{
    #[Assert\Uuid]
    private Uuid $id;

    #[Assert\Length(min: 5)]
    private string $address;

    #[Assert\Length(min: 5, max: 5)]
    private string $postalCode;

    #[Assert\Length(min: 2)]
    private string $city;

    public function getId(): Uuid
    {
        return $this->id;
    }

    public function setId(Uuid $id): CommandContactEditAddress
    {
        $this->id = $id;

        return $this;
    }

    public function getAddress(): string
    {
        return $this->address;
    }

    public function setAddress(string $address): CommandContactEditAddress
    {
        $this->address = $address;

        return $this;
    }

    public function getPostalCode(): string
    {
        return $this->postalCode;
    }

    public function setPostalCode(string $postalCode): CommandContactEditAddress
    {
        $this->postalCode = $postalCode;

        return $this;
    }

    public function getCity(): string
    {
        return $this->city;
    }

    public function setCity(string $city): CommandContactEditAddress
    {
        $this->city = $city;

        return $this;
    }
}

src/Entity/Command/Contact/CommandContactEditEmail.php
<?php

namespace App\Entity\Command\Contact;

use App\CQRS\Entity\Command\CommandEntityInterface;
use Symfony\Component\Uid\Uuid;
use Symfony\Component\Validator\Constraints as Assert;

class CommandContactEditEmail implements CommandEntityInterface
{
    #[Assert\Uuid]
    private Uuid $id;

    #[Assert\Email]
    private string $email;

    public function getId(): Uuid
    {
        return $this->id;
    }

    public function setId(Uuid $id): CommandContactEditEmail
    {
        $this->id = $id;

        return $this;
    }

    public function getEmail(): string
    {
        return $this->email;
    }

    public function setEmail(string $email): CommandContactEditEmail
    {
        $this->email = $email;

        return $this;
    }
}

src/Entity/Command/Contact/CommandContactEditFamillyName.php
<?php

namespace App\Entity\Command\Contact;

use App\CQRS\Entity\Command\CommandEntityInterface;
use Symfony\Component\Uid\Uuid;
use Symfony\Component\Validator\Constraints as Assert;

class CommandContactEditFamillyName implements CommandEntityInterface
{
    #[Assert\Uuid]
    private Uuid $id;

    #[Assert\Length(min: 0, max: 64)]
    private string $famillyName;

    public function getId(): Uuid
    {
        return $this->id;
    }

    public function setId(Uuid $id): CommandContactEditFamillyName
    {
        $this->id = $id;

        return $this;
    }

    public function getFamillyName(): string
    {
        return $this->famillyName;
    }

    public function setFamillyName(string $famillyName): CommandContactEditFamillyName
    {
        $this->famillyName = $famillyName;

        return $this;
    }
}

src/Entity/Command/Contact/CommandContactEditGivenName.php
<?php

namespace App\Entity\Command\Contact;

use App\CQRS\Entity\Command\CommandEntityInterface;
use Symfony\Component\Uid\Uuid;
use Symfony\Component\Validator\Constraints as Assert;

class CommandContactEditGivenName implements CommandEntityInterface
{
    #[Assert\Uuid]
    private Uuid $id;

    #[Assert\Length(min: 0, max: 64)]
    private string $givenName;

    public function getId(): Uuid
    {
        return $this->id;
    }

    public function setId(Uuid $id): CommandContactEditGivenName
    {
        $this->id = $id;

        return $this;
    }

    public function getGivenName(): string
    {
        return $this->givenName;
    }

    public function setGivenName(string $givenName): CommandContactEditGivenName
    {
        $this->givenName = $givenName;

        return $this;
    }
}

src/Entity/Command/Contact/CommandContactEditName.php
<?php

namespace App\Entity\Command\Contact;

use App\CQRS\Entity\Command\CommandEntityInterface;
use Symfony\Component\Uid\Uuid;
use Symfony\Component\Validator\Constraints as Assert;

class CommandContactEditName implements CommandEntityInterface
{
    #[Assert\Uuid]
    private Uuid $id;

    #[Assert\Length(min: 2)]
    private string $name;

    public function getId(): Uuid
    {
        return $this->id;
    }

    public function setId(Uuid $id): CommandContactEditName
    {
        $this->id = $id;

        return $this;
    }

    public function getName(): string
    {
        return $this->name;
    }

    public function setName(string $name): CommandContactEditName
    {
        $this->name = $name;

        return $this;
    }
}

src/Entity/Command/Contact/CommandContactEditPhone.php
<?php

namespace App\Entity\Command\Contact;

use App\CQRS\Entity\Command\CommandEntityInterface;
use Symfony\Component\Uid\Uuid;
use Symfony\Component\Validator\Constraints as Assert;

class CommandContactEditPhone implements CommandEntityInterface
{
    #[Assert\Uuid]
    private Uuid $id;

    #[Assert\Length(min: 10, max: 20)]
    private string $phone;

    public function getId(): Uuid
    {
        return $this->id;
    }

    public function setId(Uuid $id): CommandContactEditPhone
    {
        $this->id = $id;

        return $this;
    }

    public function getPhone(): string
    {
        return $this->phone;
    }

    public function setPhone(string $phone): CommandContactEditPhone
    {
        $this->phone = $phone;

        return $this;
    }
}

src/Entity/Event/Contact/EventContactDelete.php
<?php

namespace App\Entity\Event\Contact;

use App\CQRS\Entity\Event\EventDataInterface;
use Symfony\Component\Uid\Uuid;

class EventContactDelete implements EventDataInterface
{
    private Uuid $id;

    public function getId(): Uuid
    {
        return $this->id;
    }

    public function setId(Uuid $id): EventContactDelete
    {
        $this->id = $id;

        return $this;
    }
}

src/Entity/Event/Contact/EventContactEditAddress.php
<?php

namespace App\Entity\Event\Contact;

use App\CQRS\Entity\Event\EventDataInterface;
use Symfony\Component\Uid\Uuid;

class EventContactEditAddress implements EventDataInterface
{
    private Uuid $id;

    private string $address;

    private string $postalCode;

    private string $city;

    public function getId(): Uuid
    {
        return $this->id;
    }

    public function setId(Uuid $id): EventContactEditAddress
    {
        $this->id = $id;

        return $this;
    }

    public function getAddress(): string
    {
        return $this->address;
    }

    public function setAddress(string $address): EventContactEditAddress
    {
        $this->address = $address;

        return $this;
    }

    public function getPostalCode(): string
    {
        return $this->postalCode;
    }

    public function setPostalCode(string $postalCode): EventContactEditAddress
    {
        $this->postalCode = $postalCode;

        return $this;
    }

    public function getCity(): string
    {
        return $this->city;
    }

    public function setCity(string $city): EventContactEditAddress
    {
        $this->city = $city;

        return $this;
    }
}

src/Entity/Event/Contact/EventContactEditEmail.php
<?php

namespace App\Entity\Event\Contact;

use App\CQRS\Entity\Event\EventDataInterface;
use Symfony\Component\Uid\Uuid;

class EventContactEditEmail implements EventDataInterface
{
    private Uuid $id;

    private string $email;

    public function getId(): Uuid
    {
        return $this->id;
    }

    public function setId(Uuid $id): EventContactEditEmail
    {
        $this->id = $id;

        return $this;
    }

    public function getEmail(): string
    {
        return $this->email;
    }

    public function setEmail(string $email): EventContactEditEmail
    {
        $this->email = $email;

        return $this;
    }
}

src/Form/Type/Contact/ContactCreateType.php
<?php

namespace App\Form\Type\Contact;

use App\Entity\Command\Contact\CommandContactCreate;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\EmailType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ContactCreateType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('name', TextType::class)
            ->add('givenName', TextType::class)
            ->add('famillyName', TextType::class)
            ->add('email', EmailType::class)
            ->add('phone', TextType::class)
            ->add('address', TextType::class)
            ->add('postalCode', TextType::class)
            ->add('city', TextType::class);
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => CommandContactCreate::class,
        ]);
    }
}

src/Form/Type/Contact/ContactDeleteType.php
<?php

namespace App\Form\Type\Contact;

use App\Entity\Command\Contact\CommandContactDelete;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\UuidType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ContactDeleteType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('id', UuidType::class, ['attr' => ['class' => 'd-none'], 'label_attr' => ['class' => 'd-none']]);
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => CommandContactDelete::class,
        ]);
    }
}

src/Form/Type/Contact/ContactEditAddressType.php
<?php

namespace App\Form\Type\Contact;

use App\Entity\Command\Contact\CommandContactEditAddress;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\UuidType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ContactEditAddressType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('id', UuidType::class, ['attr' => ['class' => 'd-none'], 'label_attr' => ['class' => 'd-none']])
            ->add('address', TextType::class)
            ->add('postalCode', TextType::class)
            ->add('city', TextType::class);
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => CommandContactEditAddress::class,
        ]);
    }
}

src/CQRS/Controller/AbstractCommandController.php
<?php

namespace App\CQRS\Controller;

use App\Controller\Query\Contact\QueryContactDetailController;
use App\CQRS\Attribute\AsCommandController;
use App\CQRS\Entity\Command\CommandEntityInterface;
use App\CQRS\Entity\Event\EventDataInterface;
use App\CQRS\Entity\Event\EventEntity;
use App\CQRS\Factory\EventEntityFactory;
use App\CQRS\Repository\Event\EventEntityRepository;
use Exception;
use ReflectionClass;
use RuntimeException;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\EventDispatcher\EventDispatcherInterface;
use Symfony\Component\Form\FormInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpKernel\Exception\AccessDeniedHttpException;
use Symfony\Component\HttpKernel\Exception\BadRequestHttpException;
use Symfony\Component\HttpKernel\HttpKernelInterface;

abstract class AbstractCommandController extends AbstractController
{

    protected string $commandClassName;
    protected string $formTypeClassName;

    public function __construct()
    {
        $reflexionAttibuttes = (new ReflectionClass($this))->getAttributes(AsCommandController::class);

        if (count($reflexionAttibuttes) === 0) {
            throw new RuntimeException(self::class . ' must have AsCommandController attribute');
        }

        $attributeArguments = $reflexionAttibuttes[0]->getArguments();
        $this->commandClassName = $attributeArguments['commandClassName'];
        $this->formTypeClassName = $attributeArguments['formTypeClassName'];
    }

    public function __invoke(
        Request                  $request,
        EventDispatcherInterface $dispatcher,
        EventEntityFactory       $eventEntityFactory,
        EventEntityRepository    $eventEntityRepository,
        HttpKernelInterface      $httpKernel
    ): Response
    {
        /** @var CommandEntityInterface $commandEntity */
        $commandEntity = new $this->commandClassName();

        $form = $this->createForm($this->formTypeClassName, $commandEntity);
        $form->handleRequest($request);

        if (!$form->isValid()) {
            return $this->onFormError($request, $form, $httpKernel);
        }

        if (!$this->isValid()) {
            throw new BadRequestHttpException('Invalid data');
        }

        if (!$this->isAuthorized($commandEntity)) {
            throw new AccessDeniedHttpException();
        }

        $event = $eventEntityFactory->createEvent($this->toEventDataEntity($commandEntity));

        $eventEntityRepository->add($event);

        $dispatcher->dispatch($event);

        return $this->getResponse($event);
    }

    protected function isValid(): bool
    {
        return true;
    }

    protected function isAuthorized(CommandEntityInterface $commandEntity): bool
    {
        return true;
    }

    abstract protected function toEventDataEntity(CommandEntityInterface $commandEntity): EventDataInterface;

    abstract protected function getResponse(EventEntity $eventEntity): Response;

    protected function onFormError(Request $request, FormInterface $form, HttpKernelInterface $httpKernel): Response
    {
        throw new BadRequestHttpException('Invalid data');
    }

    /**
     * @throws Exception
     */
    protected function handelSubController(Request $request, FormInterface $form, HttpKernelInterface $httpKernel, string $controller, array $attributes = []): Response
    {
        $subAttributes = [...$request->attributes->all(), ...$attributes];
        $subAttributes['_controller'] = QueryContactDetailController::class;
        $subRequest = $request->duplicate(null, null, $subAttributes);
        return $httpKernel->handle($subRequest, HttpKernelInterface::SUB_REQUEST);
    }
}

templates/contact/create.html.twig
{% extends 'base.html.twig' %}

{% block title %}
	Create New Contact
{% endblock %}

{% block body %}
	<div class="card shadow-sm mt-5 mb-5 rounded">
		<div class="card-body">
			<h2 class="card-title">Ajouter un nouveau contact</h2>
			{{ form_start(form, {attr: {class: 'ms-3', action: path('contact_create'), 'method': 'POST'}}) }}
			<div class="row">
				{{ form_row(form.name, {attr: {class: 'form-control'}}) }}
				{{ form_errors(form.name) }}
				{{ form_row(form.givenName, {attr: {class: 'form-control'}}) }}
				{{ form_errors(form.givenName) }}
				{{ form_row(form.famillyName, {attr: {class: 'form-control'}}) }}
				{{ form_errors(form.famillyName) }}
				{{ form_row(form.email, {attr: {class: 'form-control'}}) }}
				{{ form_errors(form.email) }}
				{{ form_row(form.phone, {attr: {class: 'form-control'}}) }}
				{{ form_errors(form.phone) }}
				{{ form_row(form.address, {attr: {class: 'form-control'}}) }}
				{{ form_errors(form.address) }}
				{{ form_row(form.postalCode, {attr: {class: 'form-control'}}) }}
				{{ form_errors(form.postalCode) }}
				{{ form_row(form.city, {attr: {class: 'form-control'}}) }}
				{{ form_errors(form.city) }}
				<button type="submit" class="btn btn-primary form-control mt-5"><i class="fa-solid fa-check"></i>Valider
				</button>
			</div>
			{{ form_end(form) }}
		</div>
	</div>
{% endblock %}

templates/contact/detail.html.twig
{% extends 'base.html.twig' %}
{% block body %}
	<div class="card shadow-sm mt-5 mb-5 rounded">
		<div class="card-body">
			<hgroup>
				<h2 class="card-title editName collapse {% if not formName.vars.submitted or formName.vars.valid %}show{% endif %}">{{ contact.name }}</h2>
				{% if not formName.vars.submitted or formName.vars.valid %}
					{{ form_start(formName, {attr: {class: 'collapse multi-collapse editName ms-3', action: path('contact_edit_name')}}) }}
				{% else %}
					{{ form_start(formName, {attr: {class: 'collapse multi-collapse editName ms-3 show', action: path('contact_edit_name')}}) }}
				{% endif %}

				<div class="d-flex">
					<div class="col-auto">
						{{ form_widget(formName.name, {attr: {class: 'form-control'}}) }}
						{{ form_errors(formName.name) }}
					</div>
					<button type="submit" class="btn btn-primary ms-auto"><i class="fa-solid fa-check"></i> Valider
					</button>
				</div>
				{{ form_end(formName) }}

				<a class="btn btn-light btn-sm fa-solid fa-pencil ms-auto" data-bs-toggle="collapse"
				   data-bs-target=".editName"></a>
			</hgroup>

			<ul class="list-group list-group-flush">
				<li class="list-group-item d-flex "><strong>Prénom : </strong>
					<span class="ms-1 editGivenName collapse {% if not formGivenName.vars.submitted or formGivenName.vars.valid %}show{% endif %}">{{ contact.giveName }}</span>

					{% if not formName.vars.submitted or formName.vars.valid %}
						{{ form_start(formGivenName, {attr: {class: 'collapse multi-collapse editGivenName ms-3', action: path('contact_edit_name')}}) }}
					{% else %}
						{{ form_start(formGivenName, {attr: {class: 'collapse multi-collapse editGivenName ms-3 show', action: path('contact_edit_name')}}) }}
					{% endif %}
					<div class="d-flex">
						<div class="col-auto">
							{{ form_widget(formGivenName.givenName, {attr: {class: 'form-control'}}) }}
							{{ form_errors(formGivenName.givenName) }}
						</div>
						<button type="submit" class="btn btn-primary ms-auto"><i class="fa-solid fa-check"></i> Valider
						</button>
					</div>
					{{ form_end(formGivenName) }}

					<a class="btn btn-light btn-sm fa-solid fa-pencil ms-auto" data-bs-toggle="collapse"
					   data-bs-target=".editGivenName"></a>
				</li>
				<li class="list-group-item d-flex"><strong>Nom : </strong>
					<span class="ms-1 editFamillyName collapse {% if not formFamillyName.vars.submitted or formFamillyName.vars.valid %}show{% endif %}">{{ contact.famillyName }}</span>

					{% if not formName.vars.submitted or formName.vars.valid %}
						{{ form_start(formFamillyName, {attr: {class: 'collapse multi-collapse editFamillyName ms-3', action: path('contact_edit_name')}}) }}
					{% else %}
						{{ form_start(formFamillyName, {attr: {class: 'collapse multi-collapse editFamillyName ms-3 show', action: path('contact_edit_name')}}) }}
					{% endif %}
					<div class="d-flex">
						<div class="col-auto">
							{{ form_widget(formFamillyName.famillyName, {attr: {class: 'form-control'}}) }}
							{{ form_errors(formFamillyName.famillyName) }}
						</div>
						<button type="submit" class="btn btn-primary ms-auto"><i class="fa-solid fa-check"></i> Valider
						</button>
					</div>
					{{ form_end(formFamillyName) }}

					<a class="btn btn-light btn-sm fa-solid fa-pencil ms-auto" data-bs-toggle="collapse"
					   data-bs-target=".editFamillyName"></a>
				</li>
				<li class="list-group-item d-flex"><strong>Adresse : </strong><br/>
					<span class="ms-1 editAddress collapse {% if not formAddress.vars.submitted or formAddress.vars.valid %}show{% endif %}">{{ contact.address }}</span><br/>
					<span class="ms-1 editAddress collapse {% if not formAddress.vars.submitted or formAddress.vars.valid %}show{% endif %}">{{ contact.postalCode }} {{ contact.city }}</span>

					{% if not formName.vars.submitted or formName.vars.valid %}
						{{ form_start(formAddress, {attr: {class: 'collapse multi-collapse editAddress ms-3', action: path('contact_edit_name')}}) }}
					{% else %}
						{{ form_start(formAddress, {attr: {class: 'collapse multi-collapse editAddress ms-3 show', action: path('contact_edit_name')}}) }}
					{% endif %}
					<div class="d-flex">
						<div class="col-auto">
							{{ form_widget(formAddress.address, {attr: {class: 'form-control'}}) }}
							{{ form_errors(formAddress.address) }}
						</div>
						<div class="col-auto">
							{{ form_widget(formAddress.postalCode, {attr: {class: 'form-control'}}) }}
							{{ form_errors(formAddress.postalCode) }}
						</div>
						<div class="col-auto">
							{{ form_widget(formAddress.city, {attr: {class: 'form-control'}}) }}
							{{ form_errors(formAddress.city) }}
						</div>
						<button type="submit" class="btn btn-primary ms-auto"><i class="fa-solid fa-check"></i> Valider
						</button>
					</div>
					{{ form_end(formAddress) }}

					<a class="btn btn-light btn-sm fa-solid fa-pencil ms-auto" data-bs-toggle="collapse"
					   data-bs-target=".editAddress"></a>
				</li>
				<li class="list-group-item d-flex"><strong>Téléphone : </strong>
					<span class="ms-1 editPhone collapse {% if not formPhone.vars.submitted or formPhone.vars.valid %}show{% endif %}">{{ contact.phone }}</span>

					{% if not formName.vars.submitted or formName.vars.valid %}
						{{ form_start(formPhone, {attr: {class: 'collapse multi-collapse editPhone ms-3', action: path('contact_edit_name')}}) }}
					{% else %}
						{{ form_start(formPhone, {attr: {class: 'collapse multi-collapse editPhone ms-3 show', action: path('contact_edit_name')}}) }}
					{% endif %}
					<div class="d-flex">
						<div class="col-auto">
							{{ form_widget(formPhone.phone, {attr: {class: 'form-control'}}) }}
							{{ form_errors(formPhone.phone) }}
						</div>
						<button type="submit" class="btn btn-primary ms-auto"><i class="fa-solid fa-check"></i> Valider
						</button>
					</div>
					{{ form_end(formPhone) }}

					<a class="btn btn-light btn-sm fa-solid fa-pencil ms-auto" data-bs-toggle="collapse"
					   data-bs-target=".editPhone"></a>
				</li>
				<li class="list-group-item d-flex"><strong>Email : </strong>
					<span class="ms-1 editEmail collapse {% if not formEmail.vars.submitted or formEmail.vars.valid %}show{% endif %}">{{ contact.email }}</span>

					{% if not formName.vars.submitted or formName.vars.valid %}
						{{ form_start(formEmail, {attr: {class: 'collapse multi-collapse editEmail ms-3', action: path('contact_edit_name')}}) }}
					{% else %}
						{{ form_start(formEmail, {attr: {class: 'collapse multi-collapse editEmail ms-3 show', action: path('contact_edit_name')}}) }}
					{% endif %}
					<div class="d-flex">
						<div class="col-auto">
							{{ form_widget(formEmail.email, {attr: {class: 'form-control'}}) }}
							{{ form_errors(formEmail.email) }}
						</div>
						<button type="submit" class="btn btn-primary ms-auto"><i class="fa-solid fa-check"></i> Valider
						</button>
					</div>
					{{ form_end(formEmail) }}

					<a class="btn btn-light btn-sm fa-solid fa-pencil ms-auto" data-bs-toggle="collapse"
					   data-bs-target=".editEmail"></a>
				</li>
			</ul>
			<hr/>


			{{ form_start(formDelete, {attr: {action: path('contact_delete')}}) }}
			{{ form_errors(formDelete) }}
			<button type="submit" class="btn btn-danger ms-auto"><i class="fa-solid fa-trash"></i> Supprimer</button>
			{{ form_end(formDelete) }}
		</div>
	</div>
{% endblock %}

{% block title %}
	{{ contact.name }}
{% endblock %}